apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-custom-role
  namespace: test
rules:
  - apiGroups:
      - "*"
    resources:
      - services
    verbs:
      - get
      - list