apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-sample-app-12
spec:
  replicas: 0
  selector:
    matchLabels:
      app: example-app-12
  template:
    metadata:
      labels:
        app: example-app-12
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80